import { Skeleton } from "@mui/material";
import React from "react";

const ChatLoading = () => {
  return (
    <div>
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />

      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
      <Skeleton
        variant="rectangular"
        className="mt-1"
        animation="wave"
        width={"100%"}
        height={30}
      />
    </div>
  );
};

export default ChatLoading;
